### ISSUE TITLE
run_td.sh smp 64 over "recommended" 32 limit ?

### ISSUE THREAD

**Issue by matti** [canonical/tdx#77] opened 2024-04-29 04:47 UTC
https://github.com/canonical/tdx/blob/3464aa81c99b35521c9290fd953d8346af1c91f8/guest-tools/run_td.sh#L46

```cat /tmp/tdx-guest-td.log
qemu-system-x86_64: -accel kvm: warning: Number of SMP cpus requested (64) exceeds the recommended cpus supported by KVM (32)
qemu-system-x86_64: -accel kvm: warning: Number of hotpluggable cpus requested (64) exceeds the recommended cpus supported by KVM (32)
```

**Comment by fanchen2** [comment] 2024-04-29 05:39
I cannot reproduce this warning, are you using the qemu released by this 23.10 tdx integration?
But we do plan to change the vcpu number to 16, already done on the branch for 24.04 https://github.com/canonical/tdx/tree/noble-24.04, will update for this main branch(for 23.10) soon.

**Comment by fanchen2** [comment] 2024-04-29 11:38
updated by https://github.com/canonical/tdx/pull/79

**Comment by hector-cao** [comment] 2024-04-30 07:41
@matti Could  you double check that the problem has been fixed and close this issue please

**Closed** 2024-05-23 14:45 UTC
