### ISSUE TITLE
Having issues enabling TDX on Supermicro server

### ISSUE THREAD

**Issue by acduroy** [canonical/tdx#144] opened 2024-06-13 09:06 UTC
Hello I'm reporting an issue, that was originally reported by our customer,  about TDX/SGX feature is not being detected on Ubuntu 24.04 Kernel 6.8 with EMU on SMCI hardware X13DEG-QT motherboard using Emeralds Rapids 8570. Both our customer and  our technical support team were using the guide from this link  https://github.com/canonical/tdx, and yet they were not successful to enable the TDX. I have attached the steps to reproduce the issue. Refer to the attached file below
[INTEL TDX Testing on EMR CPU.pdf](https://github.com/user-attachments/files/15816293/INTEL.TDX.Testing.on.EMR.CPU.pdf)

Here's to summarize the steps that were performed.
1. TDX Initialized in BIOS and DMESG indicates that the TDX module has been initialized
2.  However, when verified using BIT (BIOS Information Tool), it shows TDX feature is not being supported

With this findings, TDX/SGX feature seems being supported by the Hardware and BIOS, but Kernel 6.8 from Ubuntu 24.04 does not support it. Could you help advise how to resolve this issue?

Appreciate for any recommendation
Alec

**Comment by hector-cao** [comment] 2024-06-14 11:24
@acduroy Thanks for this valuable feedback. Even if BIT reports TDX not being enabled, can you run a TD Guest following the README's instructions ?

**Comment by acduroy** [comment] 2024-06-14 16:55
Hi thanks for quick response. We will try to create TD and will let you know how it goes.

**Comment by bktan8** [comment] 2024-06-20 17:36
@acduroy - what is the version of the BIT tool are you using?

**Comment by hector-cao** [comment] 2024-07-25 08:55
Closing since we do not have any feedback, feel free to re-open the issue if it is still relevant

**Comment by npankaj365** [comment] 2024-09-20 20:59
Hi @hector-cao,   we are facing the same issue in our Supermicro server. The TDX feature in our server's BIOS stays greyed out and could not be enabled after following the instructions as suggested. 
The hardware and BIOS definitely supports. Here are the links to specs - [Intel Xeon Gold 5512u](https://ark.intel.com/content/www/us/en/ark/products/237565/intel-xeon-gold-5512u-processor-52-5m-cache-2-10-ghz.html) and [Server Specsheet](https://www.supermicro.com/en/products/system/up/2u/sys-521c-nr). 

Based on @hector-cao's suggestion to @acduroy, I proceeded with creating a TD image and running it regardless. Creating a TD image is a success, however running it results in an error. 

```bash
user@server:~/tdx/tdx/guest-tools$ ./run_td.sh
Error: Failed to create TD VM. Please check logfile "/tmp/tdx-guest-td.log" for more information.
user@server:~/tdx/tdx/guest-tools$ cat /tmp/tdx-guest-td.log
qemu-system-x86_64: -accel kvm: vm-type tdx not supported by KVM
```


The Error message basically points to TDX not being enabled/supported. 

Hope you can help with this.

**Comment by frenchwr** [comment] 2024-09-20 21:06
Hello, could you run the `system-report.sh` script (located in the root folder of this repo) on the system and then paste the results as a comment on this issue? That may provide some clues.

**Comment by npankaj365** [comment] 2024-09-20 22:07
Hi, 
Here's the output from `system-report.sh`

```bash

### Git ref

```
14579e7f8512caeac65d7e8cf5844b6baff06907
```

### Operating system details

```
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

### Kernel version

```
6.8.0-1010-intel #17-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  9 10:21:48 UTC 2024 x86_64 x86_64 GNU/Linux
```

### TDX kernel logs

```

```

### TDX CPU instruction support

```
No TDX support in CPU according to /proc/cpuinfo
```

### Model specific registers (MSRs)

```
MK_TME_ENABLED bit: 1 (expected value: 1)
SEAM_RR bit: 0 (expected value: 1)
NUM_TDX_PRIV_KEYS: 0
SGX_AND_MCHECK_STATUS: 0 (expected value: 0)
Production platform: Production (expected value: Production)
```

### CPU details

```
 INTEL(R) XEON(R) GOLD 5512U
```

### QEMU package details

```
Status: Installed
Package: qemu-system-x86
Version: 1:8.2.2+ds-0ubuntu2+tdx1.0
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble/main amd64 Packages
```

### Libvirt package details

```
Status: Installed
Package: libvirt-clients
Version: 10.0.0-2ubuntu8.3+tdx1.1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble/main amd64 Packages
```

### OVMF package details

```
Status: Installed
Package: ovmf
Version: 2024.02-3+tdx1.0
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble/main amd64 Packages
```

### sgx-dcap-pccs package details

```
Status: Installed
Package: sgx-dcap-pccs
Version: 1.21-0ubuntu1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
```

### tdx-qgs package details

```
Status: Installed
Package: tdx-qgs
Version: 1.21-0ubuntu2.1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
```

### sgx-ra-service package details

```
Status: Installed
Package: sgx-ra-service
Version: 1.21-0ubuntu2.1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
Description: Intel(R) Software Guard Extensions Multi-Package Registration Agent Service
```

### sgx-pck-id-retrieval-tool package details

```
Status: Installed
Package: sgx-pck-id-retrieval-tool
Version: 1.21-0ubuntu2.1
APT-Sources: https://ppa.launchpadcontent.net/kobuk-team/tdx-attestation-release/ubuntu noble/main amd64 Packages
```

### QGSD service status

```
● qgsd.service - Intel(R) TD Quoting Generation Service
     Loaded: loaded (/usr/lib/systemd/system/qgsd.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-09-19 20:34:08 UTC; 1 day 1h ago
    Process: 1514 ExecStartPre=/bin/chown -R qgsd:qgsd /var/opt/qgsd/ (code=exited, status=0/SUCCESS)
    Process: 1573 ExecStartPre=/bin/chmod 0750 /var/opt/qgsd/ (code=exited, status=0/SUCCESS)
    Process: 1586 ExecStartPre=/usr/share/qgs/linksgx.sh (code=exited, status=0/SUCCESS)
    Process: 1702 ExecStart=/usr/bin/qgs (code=exited, status=0/SUCCESS)
   Main PID: 1733 (qgs)
      Tasks: 5 (limit: 618331)
     Memory: 2.9M (peak: 3.9M)
        CPU: 60ms
     CGroup: /system.slice/qgsd.service
             └─1733 /usr/bin/qgs

Sep 19 20:34:07 shs2 systemd[1]: Starting qgsd.service - Intel(R) TD Quoting Generation Service...
Sep 19 20:34:08 shs2 systemd[1]: Started qgsd.service - Intel(R) TD Quoting Generation Service.
Sep 19 20:34:08 shs2 qgsd[1733]: Added signal handler
Sep 19 20:34:08 shs2 qgsd[1733]: About to create QgsServer with num_thread = 4
Sep 19 20:34:08 shs2 qgsd[1733]: About to start main loop
```

### PCCS service status

```
● pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/usr/lib/systemd/system/pccs.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-09-19 20:34:07 UTC; 1 day 1h ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 1510 (node)
      Tasks: 15 (limit: 618331)
     Memory: 114.1M (peak: 120.1M)
        CPU: 3.453s
     CGroup: /system.slice/pccs.service
             └─1510 /usr/bin/node /opt/intel/sgx-dcap-pccs/pccs_server.js

Sep 20 01:00:00 shs2 node[1510]: 2024-09-20 01:00:00.746 [info]: Request-ID is : 3eb9ad0314784d9dbd3033167dd240c7
Sep 20 01:00:00 shs2 node[1510]: 2024-09-20 01:00:00.846 [info]: Request-ID is : c7ca7e558abd44158a790fa1ac1e954a
Sep 20 01:00:00 shs2 node[1510]: 2024-09-20 01:00:00.946 [info]: Request-ID is : aabce696ab284960b1b34634c7da521e
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.029 [info]: Request-ID is : 005d04a966eb44b58dc88038968c067e
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.197 [info]: Request-ID is : 205f54e183414397a2a7591ba2ed3a81
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.287 [info]: Request-ID is : c744fd2a1c21403c94136ca0852040e3
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.378 [info]: Request-ID is : 4f9e3588e97147f9b75cc98d7b423f09
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.470 [info]: Request-ID is : e7572ebe530549cab8460c8d95da849f
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.545 [info]: Request-ID is : a35a583bdfa54432b16a923d39a5c2b8
Sep 20 01:00:01 shs2 node[1510]: 2024-09-20 01:00:01.948 [info]: Scheduled cache refresh is completed successfully.
```

### MPA registration logs (last 30 lines)

```
[19-09-2024 06:55:38] INFO: SGX Registration Agent version: 1.21.100.3
[19-09-2024 06:55:38] INFO: Starts Registration Agent Flow.
[19-09-2024 06:55:38] INFO: SGX MP Server configuration flag indicates that Registration Server won't save encrypted platform keys.
[19-09-2024 06:55:38] INFO: Platform registration request (PLATFORM_MANIFEST) won't be send to Registration Server.
[19-09-2024 06:55:38] INFO: Please use management tool or PCKCertIDRetrievalTool to read PLATFORM_MANIFEST.
[19-09-2024 06:55:38] INFO: Finished Registration Agent Flow.
[19-09-2024 07:08:41] INFO: SGX Registration Agent version: 1.21.100.3
[19-09-2024 07:08:41] INFO: Starts Registration Agent Flow.
[19-09-2024 07:08:41] INFO: SGX MP Server configuration flag indicates that Registration Server won't save encrypted platform keys.
[19-09-2024 07:08:41] INFO: Platform registration request (PLATFORM_MANIFEST) won't be send to Registration Server.
[19-09-2024 07:08:41] INFO: Please use management tool or PCKCertIDRetrievalTool to read PLATFORM_MANIFEST.
[19-09-2024 07:08:41] INFO: Finished Registration Agent Flow.
[19-09-2024 08:34:07] INFO: SGX Registration Agent version: 1.21.100.3
[19-09-2024 08:34:07] INFO: Starts Registration Agent Flow.
[19-09-2024 08:34:07] INFO: SGX MP Server configuration flag indicates that Registration Server won't save encrypted platform keys.
[19-09-2024 08:34:07] INFO: Platform registration request (PLATFORM_MANIFEST) won't be send to Registration Server.
[19-09-2024 08:34:07] INFO: Please use management tool or PCKCertIDRetrievalTool to read PLATFORM_MANIFEST.
[19-09-2024 08:34:07] INFO: Finished Registration Agent Flow.
```

```

**Comment by bktan8** [comment] 2024-09-20 22:17
Hi @npankaj365 - Can you try going into the BIOS and loading default settings?  If TDX settings are grayed out, then this needs to be resolved with SuperMicro.

**Comment by npankaj365** [comment] 2024-09-20 22:20
Thank you for your prompt responses. I do not have access to the servers currently. I can try loading default settings and report back as soon as I get access to the server terminals. 

I will also try to get to SuperMicro about this.

**Comment by smherwig** [comment] 2024-10-09 19:22
@bktan8 - I'm on @npankaj365's team, and I figured out how to fix the problem.

To recap, our setup is:

- server: [Supermicro X13 2U CloudDC SYS-521C-NR](https://www.supermicro.com/en/products/system/up/2u/sys-521c-nr),
- cpu: [Intel Xeon Gold 5512U](https://ark.intel.com/content/www/us/en/ark/products/237565/intel-xeon-gold-5512u-processor-52-5m-cache-2-10-ghz.html)
- motherboard: [X13SEDW-F](https://www.supermicro.com/manuals/motherboard/X13/MNL-2451.pdf)
- BIOS: [X13SEDW-F_2.3_01.03.16_SUM2.14.0-p5.zip](https://www.supermicro.com/about/policies/disclaimer.cfm?SoftwareItemID=22294).  Retrieved on Oct 1, 2024 from https://www.supermicro.com/support/resources/bios_ipmi.php?type=BIOS (search for the motherboard model X13SEDW-F).

In order to make the TDX options selectable in the BIOS, the following *non-TDX* BIOS options must be set as follows:

```
Advanced -> CPU Configuration -> Limit CPU PA to 46 bits : DISABLED
Advanced -> North Bridge -> Uncore Configuration -> Memory Configuration -> Memory RAS Configuration -> Mirror Mode: DISABLED
Advanced -> CPU Configuration -> Advanced Power Management Configuration -> Extended API: ENABLE
```

The  last two were already correct (and presumably the default), but I had to toggle the `Limit CPU to 46 bits` from `ENABLE` to `DISABLED`.  Once I did that, the TDX options became selectable.

**Comment by bktan8** [comment] 2024-10-09 19:30
Great job @smherwig!!!  Thanks for sharing and we'll pass it along to other SuperMicro users.

After all this, is TDX working for you?

**Comment by npankaj365** [comment] 2024-10-10 19:10
@bktan8 - We were trying to complete all the steps from the README.md before reporting back. We aren't able to complete the attestation steps after [Step 9.3](https://www.intel.com/content/www/us/en/security/trust-authority.html). Step 9.3 requires an account in Intel Tiber Trust Service. At the moment, we're waiting to receive an API key from the Intel Tiber Trust Service. 
TDX seems to be available and working in the host and guest, however.

**Comment by bktan8** [comment] 2024-10-10 22:49
@npankaj365 - Please let me know if you get stuck.  I might be able to find some help.

**Comment by npankaj365** [comment] 2024-10-16 18:53
Hi @bktan8 - We wanted to wait and see if we could receive an API key from the Intel Tiber Trust Service. It has been a week since we signed up and haven't received anything. It's safe to say we are stuck and would appreciate your help with the next steps.

**Comment by bktan8** [comment] 2024-10-16 19:06
Ok - Let me see if I can get some help for you.

**Comment by MattHIntel** [comment] 2024-10-16 19:29
We wanted to wait and see if we could receive an API key from the Intel Tiber Trust Service. It has been a week since we signed up and haven't received anything. It's safe to say we are stuck and would appreciate your help with the next steps.

Hi @npankaj365 - for some reason I do not see a request. Could you please fill out the form here by clicking on the "Request Free Trial" button - https://www.intel.com/content/www/us/en/security/trust-authority.html

This will go directly to me.

**Comment by npankaj365** [comment] 2024-10-16 19:37
@MattHIntel -  I just did.

**Comment by MattHIntel** [comment] 2024-10-17 19:10
Hi Pankaj,

May I ask if you have registered your platform.  Intel Trust Authority requires a product platform to be registered for the verification to work.
This is the typical method that is used to register the platform.

https://cc-enabling.trustedservices.intel.com/intel-tdx-enabling-guide/02/infrastructure_setup/#online-automatic-single-platform-direct-registration


Matt Horany
Director – SW/SaaS – Strategic Partnerships
SMG
(972) 827-8827

**Comment by npankaj365** [comment] 2024-10-17 21:34
I have done the necessary steps from Online Automatic Single Platform Direct Registration, and on checking if the registration is successful by running `cat /var/log/mpa_registration.log` get the following output at the end. 
```
[17-10-2024 03:24:51] INFO: SGX Registration Agent version: 1.21.100.3
[17-10-2024 03:24:51] INFO: Starts Registration Agent Flow.
[17-10-2024 03:24:51] INFO: Registration Flow - Registration status indicates registration is completed successfully. MPA has nothing to do.
[17-10-2024 03:24:51] INFO: Finished Registration Agent Flow.
```
I believe that confirms that platform is registered. 

However running the `trustauthority-cli token -c config.json` still results in the same output. 
Something I noticed that was peculiar and don't understand is that I am not able to `ping` to any websites in the internet but can access the page through `curl` or `wget`. For a minute, I was wondering if the TD guest did not have access to internet, but realized later that not to be the case. My suspicion is that there is a chance the request is not getting to the service in Internet based on the message `"... or the URL is not accessible...."`.

**Comment by MattHIntel** [comment] 2024-10-18 16:01
Hi Pankaj,

I'm cc'ing my colleague on this while I'm out of office.  Let us look into this for you.

The trust authority client follows any configured proxy information on the system environment variable.  If it's not reaching the Internet it sounds like this could be related to a technical challenge with proxy of network configuration.

Matt Horany
Director – SW/SaaS – Strategic Partnerships
SMG
(972) 827-8827

**Comment by MattHIntel** [comment] 2024-10-28 19:41
Hi Pankaj,

Were you able to reach the URL from that server?  I wanted to reach out and see what additional help/troubleshooting we could provide.

Matt Horany
Director - SW/SaaS - Strategic Partnerships
SMG
(972) 827-8827

From: Horany, Matt
Sent: Friday, October 18, 2024 11:01 AM
To: canonical/tdx ***@***.***>; canonical/tdx ***@***.***>
Cc: Mention ***@***.***>; Thinagarajan, Bala ***@***.***>
Subject: RE: [canonical/tdx] Having issues enabling TDX on Supermicro server (Issue #144)

Hi Pankaj,

I'm cc'ing my colleague on this while I'm out of office.  Let us look into this for you.

The trust authority client follows any configured proxy information on the system environment variable.  If it's not reaching the Internet it sounds like this could be related to a technical challenge with proxy of network configuration.

Matt Horany
Director - SW/SaaS - Strategic Partnerships
SMG
(972) 827-8827

**Comment by npankaj365** [comment] 2024-10-28 20:26
Hi @MattHIntel, we are still stuck in the same place. I was waiting for your colleague to respond. I have confirmed from my end that the internet is accessible. It was just the ICMP packets that were dropped. 

How do you suggest we move forward?

**Comment by npankaj365** [comment] 2024-11-14 17:10
@MattHIntel - Bumping this up, just in case it slipped under other things. We're still waiting for your response and support. 

Thanks!

**Closed** 2024-11-15 15:01 UTC
Labels: question

**Comment by bktan8** [comment] 2024-11-15 15:30
> @MattHIntel - Thank you very much for your clarification. It seems I was using the Admin API Keys, which was why the issue persisted. The steps leading up to successful attestation token generation are finally done. Thanks to everyone involved.
> 
> Just so someone does not end up getting confused like I did, I have made a pull request with the necessary modification in the README.md to make the type of API keys explicit [here](https://github.com/canonical/tdx/pull/274).

Thank you for your contribution @npankaj365!

**Comment by liho00** [comment] 2025-04-08 15:47
@acduroy Hi, may i know where to install  BIT (BIOS Information Tool)?
