### ISSUE TITLE
Can I use VTune in TDX?

### ISSUE THREAD

**Issue by hedj17** [canonical/tdx#182] opened 2024-07-30 03:15 UTC
I want to use VTune in TDX to analyze program performance, but when I use VTune, the virtual machine's state changes to paused. What should I do if I want to use VTune or other performance analysis tools, or is this prohibited in TDX?

**Comment by bktan8** [comment] 2024-07-30 22:48
Hello @hedj17 - Can you provide more details?

1) Provide steps to reproduce.  Versions of software would also be helpful.  
2) Are you trying to profile userspace components within the VM or are you trying to profile hardware events?

**Comment by hedj17** [comment] 2024-08-01 09:17
@bktan8 when I run `vtune-gui` command in VM，the VM's state changes to paused which is independent of  profile content.

I used tdx1.5 and the version of vtune is 2024.2

**Comment by bktan8** [comment] 2024-08-01 14:43
@hedj17 - can you try the non-GUI version of vtune inside the TD?

**Comment by fanchen2** [comment] 2024-08-05 10:37
@hedj17 I have no experience on VTune, but just remembered "pmu" is not supported in this TDX software stack, and because of this, perf cannot run properly in TD guest either.

**Comment by hedj17** [comment] 2024-08-05 10:55
@fanchen2 
Thank you for your response. Is there any way for me to obtain the performance metrics of a program running in a TD guest?

**Comment by BFuhry** [comment] 2024-08-14 10:30
@hedj17 Could you please try to start a Trust Domain (TD) with the PERFMON attribute set? For QEMU boot, you can set the attributes used during TD boot via QEMU command line parameters. For libvirt boot, you can set the attributes used during TD boot via the policy in the launchSecurity element of your template xml.

Table 3.9 in https://cdrdv2.intel.com/v1/dl/getContent/733579 lists all the attributes of a TD, in particular PERFMON. Additionally, you can find more information about performance measurements in a TD in https://cdrdv2.intel.com/v1/dl/getContent/733575. In particular, section 15.2 will give you some details.

**Comment by hector-cao** [comment] 2024-12-05 14:41
@hedj17 Hello, do you think we can close this issue ?

**Closed** 2024-12-12 07:45 UTC
