### ISSUE TITLE
guest-tools: image: virt-customize fails to create the guest image

### ISSUE THREAD

**Issue by fidencio** [canonical/tdx#133] opened 2024-06-05 12:02 UTC
```
sdp@984fee00bd70:~/tdx/guest-tools/image$ sudo -E ./create-td-image.sh 
SUCCESS: Installation of required tools
--2024-06-05 04:59:22--  https://cloud-images.ubuntu.com/releases/noble/release//SHA256SUMS
Resolving proxy-dmz.intel.com (proxy-dmz.intel.com)... 10.7.211.16
Connecting to proxy-dmz.intel.com (proxy-dmz.intel.com)|10.7.211.16|:912... connected.
Proxy request sent, awaiting response... 200 OK
Length: 7629 (7.5K)
Saving to: ‘SHA256SUMS’

SHA256SUMS                                            100%[======================================================================================================================>]   7.45K  --.-KB/s    in 0.01s   

2024-06-05 04:59:23 (506 KB/s) - ‘SHA256SUMS’ saved [7629/7629]

SUCCESS: Verify the checksum for Ubuntu cloud image.
SUCCESS: Copy the ubuntu-24.04-server-cloudimg-amd64.img => /tmp/tdx-guest-ubuntu-24.04-generic.qcow2
Image resized.
[   0.0] Examining the guest ...
virt-customize: error: libguestfs error: passt exited with status 1

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]
WARN: Failed to resize guest image to 50G
~/tdx/guest-tools/image/cloud-init-data ~/tdx/guest-tools/image
SUCCESS: Generate configuration for cloud-init...
I: -input-charset not specified, using utf-8 (detected in locale settings)
Total translation table size: 0
Total rockridge attributes bytes: 331
Total directory bytes: 0
Path table size(bytes): 10
Max brk space used 0
183 extents written (0 MB)
SUCCESS: Generate the cloud-init ISO image...
~/tdx/guest-tools/image
SUCCESS: Complete cloud-init...
[   0.0] Examining the guest ...
virt-customize: error: libguestfs error: passt exited with status 1

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]
ERROR: Failed to setup guest image
SUCCESS: Cleanup!
```

**Comment by hector-cao** [comment] 2024-06-05 22:47
Thanks @fidencio In the past, i saw this kind of failure without being able to reproduce it easily, can you reproduce it ?

**Comment by fidencio** [comment] 2024-06-24 15:01
> Thanks @fidencio In the past, i saw this kind of failure without being able to reproduce it easily, can you reproduce it ?

I ended up reinstalling everything on my end, and was not able to reproduce this anymore. :-/

**Comment by hector-cao** [comment] 2024-07-24 12:51
This issue is hard to reproduce and since the issue was created; some actions have been taken
- to improve the debugging capability in case this issue will happen again 
- to improve the robustness of the script

I propose to close this issue and let see if it will re-emerge

**Closed** 2024-09-05 07:19 UTC
Labels: bug
